# Generated by Django 5.1.4 on 2024-12-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_remove_account_account_number_alter_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
